<?php

/**
 * @file
 * Handles the creation and display of binary_object Islandora objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_binary_object_theme($existing, $type, $theme, $path) {
  return [
    'islandora_binary_object' => [
      'file' => 'theme/theme.inc',
      'template' => 'islandora-binary-object',
      'pattern' => 'islandora_binary_object__',
      'variables' => ['islandora_object' => NULL],
    ],
  ];
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_binary_object_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_binary_object');
  $islandora_path = drupal_get_path('module', 'islandora');
  // Binary Object Content Model.
  $binary_object_content_model = $connection->repository->constructObject('islandora:binaryObjectCModel');
  $binary_object_content_model->owner = 'fedoraAdmin';
  $binary_object_content_model->label = 'Islandora Binary Object Content Model';
  $binary_object_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $binary_object_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_binary_object_ds_composite_model.xml", FALSE);
  $binary_object_content_model->ingestDatastream($datastream);
  // Image Collection.
  $binary_object_collection = $connection->repository->constructObject('islandora:binary_object_collection');
  $binary_object_collection->owner = 'fedoraAdmin';
  $binary_object_collection->label = 'Binary Object Collection';
  $binary_object_collection->models = 'islandora:collectionCModel';
  $binary_object_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $binary_object_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_binary_object_collection_policy.xml", FALSE);
  $binary_object_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $binary_object_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $binary_object_collection->ingestDatastream($datastream);
  return [
    'islandora_binary_object' => [
      'title' => 'Islandora Binary Object',
      'objects' => [
        $binary_object_content_model,
        $binary_object_collection,
      ],
    ],
  ];
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_binary_object_xml_form_builder_form_associations() {
  return [
    'islandora_binary_object_mods_form' => [
      'content_model' => 'islandora:binaryObjectCModel',
      'form_name' => 'Binary Object MODS form',
      'dsid' => 'MODS',
      'title_field' => ['titleInfo', 'title'],
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ],
  ];
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_binary_object_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_binary_object');
  return [
    'Binary Object MODS form' => [
      'form_file' => "$module_path/xml/islandora_binary_object_form_mods.xml",
    ],
  ];
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_binary_object_islandora_binaryobjectcmodel_islandora_ingest_steps() {
  return [
    'islandora_binary_object' => [
      'weight' => 10,
      'type' => 'form',
      'form_class' => 'Drupal\islandora_binary_object\Form\UploadForm',
      'module' => 'islandora_binary_object',
      'file' => 'includes/binary_object_upload.form.inc',
    ],
  ];
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_binary_object_islandora_binaryobjectcmodel_islandora_view_object(AbstractObject $object) {
  return [
    // XXX: Because islandora_as_renderable_array isn't the best we are going to
    // wrap this in an array.
    '' => [
      [
        '#theme' => 'islandora_binary_object',
        '#islandora_object' => $object,
      ],
    ],
  ];
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_binary_object_islandora_binaryobjectcmodel_islandora_derivative() {
  return [
    [
      'source_dsid' => NULL,
      'destination_dsid' => 'TN',
      'weight' => '0',
      'function' => [
        'islandora_binary_object_create_thumbnail',
      ],
      'file' => drupal_get_path('module', 'islandora_binary_object') . '/includes/derivatives.inc',
    ],
  ];
}
